# Generated by Django 5.0.6 on 2024-06-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='media/default.png', upload_to='productos/'),
        ),
    ]
